tap 'beeftornado/rmtree'
tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/services'
brew 'git'
brew 'asciinema'
brew 'bash'
brew 'coreutils'
brew 'fasd'
brew 'python'
brew 'gcc'
brew 'gnu-sed', args: ['with-default-names']
brew 'htop'
brew 'hub'
brew 'irssi'
brew 'lesspipe', args: ['with-syntax-highlighting']
brew 'python3'
brew 'macvim', args: ['with-lua', 'with-override-system-vim']
brew 'mpv', args: ['with-bundle']
brew 'neofetch'
brew 'node'
brew 'p7zip'
brew 'poppler'
brew 'pv'
brew 'ranger'
brew 'reattach-to-user-namespace'
brew 'rlwrap'
brew 'stow'
brew 'the_platinum_searcher'
brew 'tmux'
brew 'trash'
brew 'wget'
brew 'beeftornado/rmtree/brew-rmtree'
brew 'homebrew/python/numpy'
cask 'dropbox'
cask 'easy-move-plus-resize'
cask 'flux'
cask 'goofy'
cask 'google-chrome'
cask 'phoenix'
cask 'steam'
cask 'telegram'
cask 'textual'
cask 'vox'
cask 'vox-preferences-pane'
