   NAME="{{ scheme_name }}"
     BG={{ bgc | nohash }}
     FG={{ fgc | nohash }}
 SEL_BG={{ n_primary | nohash }}
 SEL_FG={{ fgc | nohash }}
 TXT_BG={{ n_black | nohash }}
 TXT_FG={{ fgc | nohash }}
MENU_BG={{ bgc | nohash }}
MENU_FG={{ fgc | nohash }}
 BTN_BG={{ b_black | nohash }}
 BTN_FG={{ fgc | nohash }}
