__variables__:
    mpvfifo: ~/.local/share/mpv/fifo
mpv:
    rewind: echo seek -5 > {mpvfifo}
    play/pause: echo cycle pause > {mpvfifo}
    fast forward: echo seek 5 > {mpvfifo}
cliclick:
    left: cliclick kp:arrow-left
    spacebar: cliclick kp:space
    right: cliclick kp:arrow-right
announcer:
    greet: say hello
    part: say farewell
volume:
    0: osascript -e "set Volume 0"
    1: osascript -e "set Volume 1"
    2: osascript -e "set Volume 2"
    3: osascript -e "set Volume 3"
    4: osascript -e "set Volume 4"
    5: osascript -e "set Volume 5"
    6: osascript -e "set Volume 6"
    7: osascript -e "set Volume 7"
