__variables__:
    mpvfifo: ~/.local/share/mpv/fifo
mpv:
    rewind: echo seek -5 > {mpvfifo}
    play/pause: echo cycle pause > {mpvfifo}
    fast forward: echo seek 5 > {mpvfifo}
cliclick:
    left: cliclick kp:arrow-left
    spacebar: cliclick kp:space
    right: cliclick kp:arrow-right
announcer:
    greet: say hello
    part: say farewell
volume:
    0: osascript -e "set Volume 0"
    10: osascript -e "set Volume 10"
    20: osascript -e "set Volume 20"
    30: osascript -e "set Volume 30"
    40: osascript -e "set Volume 40"
    50: osascript -e "set Volume 50"
    60: osascript -e "set Volume 60"
    70: osascript -e "set Volume 70"
    80: osascript -e "set Volume 80"
    90: osascript -e "set Volume 90"
    100: osascript -e "set Volume 100"
