#!/usr/bin/env bash

set -e
DOTS=~/.dots
DEPS=~/.local/deps

get_ready() {
  unset ready
  while [ "$ready" != y ]; do
    read -rp "Enter 'y' when you are ready." ready
  done
}

cd

if [ ! -d "$DOTS" ]; then
  echo "Cloning .dots into $DOTS..."
  git clone git@github.com:metakirby5/.dots.git
else
  echo "$DOTS detected."
fi

echo "Please do the following:"
echo "    - Install Xcode from the App Store."
echo "    - Import the Terminal.app profile in \
misc/osx/terminal/Japanesque.terminal."
get_ready

if ! which brew &>/dev/null; then
  echo "Installing brew..."
  /usr/bin/ruby -e "$(curl -fsSL \
    https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! which stow &>/dev/null; then
  echo "Installing stow using brew..."
  brew install stow
fi

echo "Stowing base and osx..."
cd "$DOTS"
stow base osx --no-folding

echo "Installing brew dependencies..."
brew bundle --file=- < "$DEPS/brew"

echo "Changing your shell (sudo required)..."
grep '/usr/local/bin/bash' /etc/shells &>/dev/null ||
  sudo echo /usr/local/bin/bash >> /etc/shells
chsh -s /usr/local/bin/bash

echo "Modifying ~/.bashrc and ~/.bash_profile..."
grep 'source ~/.posixrc' ~/.bashrc ||
  cat >> ~/.bashrc <<< 'source ~/.posixrc'
grep 'source ~/.bashrc' ~/.bash_profile ||
  cat >> ~/.bash_profile <<< 'source ~/.bashrc'
source ~/.bashrc

echo "Installing other packages..."
install-leaves

echo "Running zenbu with defaults..."
zenbu -e

echo "Setting OS X defaults..."
yes | osx-set-defaults

echo "Copying over root configs (sudo required)..."
sudo cp "$DOTS/misc/shell/root_bashrc.sh" /var/root/.bash_profile
sudo ln -s ~/.vimrc /var/root/.vimrc

echo "Done! For post-install:"
echo "  - Tweak any other settings (keybinds, etc.) in Preferences.app"
echo "  - Install the apps in ~/.local/deps/AppStore"
echo "  - Configure apps (browsers, brew cask-installed, etc.)"
